# To get started with Dependabot version updates, you'll need to specify, which
# package ecosystems to update and where the package manifests are located.
# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "monthly"
    groups:
      kotlin-kotlinx:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      android-androidx:
        patterns:
          - "com.android.*"
          - "androidx.*"
      gradle-plugins:
        patterns:
          - "gradle"
          - "com.gradle*"
          - "com.vanniktech*"
          - "org.jetbrains.dokka*"
          - "org.jetbrains.kotlinx.binary-compatibility-validator*"
          - "org.jetbrains.kotlinx.kover*"
          - "com.osacky.doctor*"
      fluxo-plugins:
        patterns:
          - "io.github.fluxo-kt*"
    reviewers:
      - "amal"
    labels:
      - "gradle"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(GitHub)"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - "amal"
    labels:
      - "gh-action"
      - "dependencies"
