# https://detekt.github.io/detekt/configurations.html
# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/resources/config/config.yml

config:
  validation: false
  warningsAsErrors: false
  checkExhaustiveness: false

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'MdOutputReport'

console-reports:
  active: true
  exclude: [ ]

exceptions:
  TooGenericExceptionCaught:
    active: false

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: false
    ignoreDeprecated: true
    ignoreOverridden: true
    ignoreAnnotatedFunctions: ['Preview']

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  MatchingDeclarationName:
    active: false

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
  MagicNumber:
    ignoreAnnotation: true
  MaxLineLength:
    maxLineLength: 100
  ReturnCount:
    max: 3
    excludeLabeled: true
    excludeGuardClauses: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']

formatting:
  ArgumentListWrapping:
    maxLineLength: 100
  BlockCommentInitialStarAlignment:
    active: true
  CommentWrapping:
    active: true
  DiscouragedCommentLocation:
    active: true
  ImportOrdering:
    active: true
    autoCorrect: true
    layout: '*'
  Indentation:
    active: false
  FunKeywordSpacing:
    active: true
  FunctionReturnTypeSpacing:
    active: true
  FunctionSignature:
    active: false
    maxLineLength: 100
  FunctionStartOfBodySpacing:
    active: true
  FunctionTypeReferenceSpacing:
    active: true
  KdocWrapping:
    active: true
  MaximumLineLength:
    maxLineLength: 100
  ModifierListSpacing:
    active: true
  NoConsecutiveBlankLines:
    active: false
  NullableTypeSpacing:
    active: true
  ParameterListWrapping:
    maxLineLength: 100
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  TrailingCommaOnCallSite:
    active: false
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: false
  TypeArgumentListSpacing:
    active: true
  TypeParameterListSpacing:
    active: true
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
  Wrapping:
    active: false
